- name: Instala programas dos laboratórios
  win_chocolatey:
    name:
      - anaconda3
      - geogebra-classic.install
      - miktex
      - python
      - r.project
      - r.studio
      - texmaker
      - texstudio
    state: present
