- name: libera grub sem senha para o OS
  lineinfile:
    path: /etc/grub.d/10_linux
    regexp: ^CLASS="--class gnu-linux --class gnu --class os"
    line: CLASS="--class gnu-linux --class gnu --class os --unrestricted"
  notify: update grub

# gerar hash com grub-mkpasswd-pbkdf2 e atribuir em grub_admir_password
- name: trava boot sem senha
  template:
    src: grub.j2
    dest: /etc/grub.d/45_password
    mode: u+rwx
  notify: update grub
