- name: libera grub sem senha para linux
  lineinfile:
    path: /etc/grub.d/10_linux
    regexp: ^CLASS="--class gnu-linux --class gnu --class os"
    line: CLASS="--class gnu-linux --class gnu --class os --unrestricted"
  notify: update grub

- name: trava boot sem senha
  template:
    src: grub.j2
    dest: /etc/grub.d/45_password
    mode: u+rwx
  notify: update grub
