- name: repositorio default
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian bullseye main contrib non-free
    filename: default

- name: repositorio security
  ansible.builtin.apt_repository:
    repo: deb https://security.debian.org/debian-security bullseye-security main contrib non-free
    filename: security

- name: repositorio updates
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian bullseye-updates main contrib non-free
    filename: updates

- name: repositorio backports
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian bullseye-backports main contrib non-free
    filename: backports
