- name: Adicionar chave do repositório do CRAN
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: 95C0FAF38DB3CCAD0C080A7BDC78B2DDEABC47B7

- name: Adicionar repositório do CRAN
  ansible.builtin.apt_repository:
    repo: deb http://cloud.r-project.org/bin/linux/debian bookworm-cran40/
    filename: rcran

- name: Instalar pacotes do R
  ansible.builtin.apt:
    update_cache: yes
    state: latest
    default_release: bookworm-cran40
    pkg:
      - r-base-dev
      - r-recommended

- name: Instalar cmake para compilação de pacotes e otimizadores sugeridos
  ansible.builtin.apt:
    pkg:
      - cmake
      - libatlas3-base
      - libopenblas0

- name: instala Rstudio
  ansible.builtin.apt:
    deb: https://si.ime.usp.br/downloads/rstudio-latest-amd64.deb
