- name: chave do repositório do miniconda
  ansible.builtin.get_url:
    url: '{{ conda_keyfile_url }}'
    dest: '{{ apt_keyring_path }}/{{ conda_keyring_file }}'
    checksum: '{{ conda_keyfile_checksum }}'

- name: arquivo do repositório do miniconda
  ansible.builtin.apt_repository:
    repo: 'deb [ signed-by={{ apt_keyring_path }}/{{ conda_keyring_file}} ] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main'
    filename: conda

- name: instala miniconda
  ansible.builtin.apt:
    update_cache: yes
    state: latest
    pkg:
      - conda

- name: pacotes dev
  apt:
    update_cache: yes
    pkg:
      - amqp-tools
      - build-essential
      - curl
      - gdb
      - git
      - jq
      - libfontconfig1-dev
      - libfribidi-dev
      - libgdal-dev
      - libgsl-dev
      - libharfbuzz-dev
      - libnode-dev
      - libproj-dev
      - libudunits2-dev
      - libx11-dev
      - nasm
      - plink1.9
      - python3-pip
      - texlive-full
      - octave
      - zstd

