- name: pacotes dev
  apt:
    update_cache: yes
    pkg:
      - amqp-tools
      - build-essential
      - curl
      - gdb
      - git
      - jq
      - libfontconfig1-dev
      - libfribidi-dev
      - libgdal-dev
      - libgsl-dev
      - libharfbuzz-dev
      - libnode-dev
      - libproj-dev
      - libudunits2-dev
      - libx11-dev
      - nasm
      - plink1.9
      - python3-pip
      - texlive-full
      - octave
      - zstd
