- name: pacotes auth
  apt:
    update_cache: yes
    pkg:
      - krb5-user
      - sssd

- name: configura krb5.conf
  copy:
    src: krb5.conf
    dest: /etc/krb5.conf

- name: instala keytab
  copy:
    src: "keytab/{{ ansible_hostname }}.keytab"
    dest: /etc/krb5.keytab

- name: certificado ldap
  copy:
    src: cacert.pem
    dest: /etc/ldap/cacert.pem

- name: configura sssd
  copy:
    src: sssd.conf
    dest: /etc/sssd/sssd.conf
    mode: 0600
  notify: reinicia sssd
