- name: pacotes lab
  apt:
    update_cache: yes
    pkg:
      - kbibtex
      - kile
      - kile-l10n
      - texlive-full
      - texmaker
      - build-essential
      - curl
      - git
      - jq
      - julia
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev
      - octave
      - python3-pip
      - r-cran-rcmdr
      - r-recommended
      - spyder
      - xfig

- name: install rstudio
  apt:
    deb: https://download1.rstudio.org/desktop/bionic/amd64/rstudio-2021.09.1-372-amd64.deb

- name: logind logout kill
  lineinfile:
    path: /etc/systemd/logind.conf
    line: 'KillUserProcesses=yes'
  notify: reinicia logind

- name: wallpaper
  copy:
    src: wallviso.png
    dest: /usr/share/backgrounds/wallviso.png

- name: configura background
  copy:
    src: dconf/background
    dest: /etc/dconf/db/local.d/00-background
  notify: dconf update

- name: wallpaper login
  copy:
    src: wallogin.png
    dest: /usr/share/backgrounds/wallogin.png

- name: configura login background
  copy:
    src: lightdm-gtk-greeter.conf.d/02_ime.conf
    dest: /usr/share/lightdm/lightdm-gtk-greeter.conf.d/02_ime.conf
