- name: logind logout kill
  lineinfile:
    path: /etc/systemd/logind.conf
    line: 'KillUserProcesses=yes'
  notify: reinicia logind

- name: configura papéis de parede
  block:
    - name: wallpaper
      copy:
        src: wallviso.png
        dest: /usr/share/backgrounds/wallviso.png

    - name: configura background
      copy:
        src: dconf/background
        dest: /etc/dconf/db/local.d/00-background
      notify: dconf update

    - name: wallpaper login
      copy:
        src: wallogin.png
        dest: /usr/share/backgrounds/wallogin.png

    - name: configura login background
      copy:
        src: lightdm-gtk-greeter.conf.d/02_ime.conf
        dest: /usr/share/lightdm/lightdm-gtk-greeter.conf.d/02_ime.conf
  when: lab_wallpaper 
  
- name: coloca o 52unattended-upgrades no apt.conf.d
  ansible.builtin.copy:
    src: apt.conf.d/52unattended-upgrades
    dest: /etc/apt/apt.conf.d/52unattended-upgrades
    owner: root
    group: root
    mode: '644'
