- name: pacotes lab
  apt:
    update_cache: yes
    pkg:
      - kbibtex
      - kile
      - kile-l10n
      - texlive-latex-recommended
      - texmaker
      - build-essential
      - curl
      - git
      - jq
      - julia
      - octave
      - python3-pip
      - r-recommended
      - spyder

- name: install rstudio
  apt:
    deb: https://download1.rstudio.org/desktop/bionic/amd64/rstudio-2021.09.1-372-amd64.deb

- name: dconf profile dir
  file:
    path: /etc/dconf/profile
    state: directory

- name: dconf user dbs
  copy:
    src: dconf/user
    dest: /etc/dconf/profile/user

- name: dconf local.d dir
  file:
    path: /etc/dconf/db/local.d
    state: directory

- name: dconf default
  copy:
    src: dconf/default
    dest: /etc/dconf/db/local.d/00-default
  notify: dconf update
