- name: pacotes dev que usam modo gráfico
  apt:
    update_cache: yes
    pkg:
      - kbibtex
      - kile
      - kile-l10n
      - texmaker
      - octave
      - spyder
      - x2goclient
      - xfig
