- name: pacotes classroom
  apt:
    update_cache: yes
    pkg:
      - kbibtex
      - kile
      - kile-l10n
      - texlive-latex-recommended
      - texmaker
      - build-essential
      - curl
      - git
      - jq
      - julia
      - octave
      - python3-pip
      - r-cran-rcmdr
      - r-recommended
      - spyder

- name: install rstudio
  apt:
    deb: https://download1.rstudio.org/desktop/bionic/amd64/rstudio-2021.09.1-372-amd64.deb

- name: adiciona usuário aula
  user:
    name: aula
    password: '{{ classroom_user_password}}'
    shell: /bin/bash

- name: configura autologin
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#autologin-user='
    line: autologin-user=aula

- name: configura screensaver
  copy:
    src: dconf/screensaver
    dest: /etc/dconf/db/local.d/01-screensaver
  notify: dconf update
